### ISSUE TITLE
Error: Cannot install 'libwebkitgtk-3.0-0:i386'

### ISSUE THREAD

**Issue by ghost** [pmullerlst/griffon-IDE#3]
Hi, I recently tried to install your deb file.
I am running 64 bit Ubuntu 14.10
3.16.0-34-lowlatency #47-Ubuntu x86_64 GNU/Linux
Do you happen to have a PPA?

**Comment by pmullerlst** [comment]
Hi,

you must install Griffon IDE with sources.
The .deb package unmaintained.

http://griffon.lasotel.fr/download/griffon.tar.gz

Doc : http://griffon.lasotel.fr/en/doc.html
